#!/usr/bin/env python3
"""
Nominal PoC test for the guardian memory/exec supervisor.

Usage (from the guardian/ project root, as root):
    sudo python3 test_guardian.py ./loader/bin/loader            # log-only mode
    sudo python3 test_guardian.py ./loader/bin/loader --enforce  # enforce mode

What it does:
  1. Writes the whitelist file the loader reads
     (loader/rsrc/whitelist_arrivals.txt by default)
  2. Starts the loader binary passed as argument and waits until it reports
     it is attached
  3. Runs the nominal cases:
       - a whitelisted binary executes (and loads its shared libraries, so
         the mmap/mprotect hooks don't break normal programs)
       - a binary outside the whitelist:
           log-only -> still executes, and a "WOULD BLOCK" line is logged
           enforce  -> is denied with EPERM
  4. Stops the loader (SIGINT) and checks the binary runs again after detach

Start in log-only mode: nothing is blocked, you only see what would be.
Don't keep `cat trace_pipe` open in another terminal during the log-only run:
trace_pipe is consumed on read, so it would steal the line this test checks.
"""

import argparse
import errno
import os
import select
import shutil
import signal
import subprocess
import sys
import time

DEFAULT_WHITELIST = "loader/rsrc/whitelist_arrivals.txt"
TRACE_PIPE = "/sys/kernel/tracing/trace_pipe"

# Binaries that must keep working while the module is attached.
# The shell and sudo keep your other terminals usable; python3 is this script.
BASE_WHITELIST = [
    "/usr/bin/bash",
    "/usr/bin/sh",
    "/usr/bin/sudo",
    "/usr/bin/cat",   # for: sudo cat /sys/kernel/tracing/trace_pipe
    os.path.realpath(sys.executable),
]

ALLOWED_TEST_BIN = "/usr/bin/ls"   # added to the whitelist, must run
DENIED_TEST_BIN = "/usr/bin/id"    # NOT in the whitelist

ATTACH_TIMEOUT_S = 10.0


# ---------------------------------------------------------------- helpers

def write_whitelist(path):
    entries = BASE_WHITELIST + [ALLOWED_TEST_BIN]
    missing = [p for p in entries if not os.path.exists(p)]
    if missing:
        sys.exit(f"[ERROR] whitelist entries not found: {missing}")

    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write("# generated by test_guardian.py\n")
        for p in entries:
            f.write(p + "\n")
    print(f"[SETUP] wrote {len(entries)} entries to {path}")


def start_loader(loader, enforce):
    cmd = [loader] + (["--enforce"] if enforce else [])
    # The loader's stdout is a pipe here, so printf() output is fully buffered
    # and "Running..." would never arrive. stdbuf forces line buffering.
    stdbuf = shutil.which("stdbuf")
    if stdbuf:
        cmd = [stdbuf, "-oL"] + cmd
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    # the loader prints "Running in ... mode" once every hook is attached
    deadline = time.monotonic() + ATTACH_TIMEOUT_S
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            sys.exit(f"[ERROR] loader exited early (code {proc.returncode}):\n{proc.stderr.read()}")
        ready, _, _ = select.select([proc.stdout], [], [], 0.2)
        if ready:
            line = proc.stdout.readline()
            if line.startswith("Running"):
                print(f"[SETUP] loader attached (pid {proc.pid}): {line.strip()}")
                return proc

    proc.kill()
    sys.exit("[ERROR] loader did not report attach in time")


def stop_loader(proc):
    proc.send_signal(signal.SIGINT)
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()
    print("[TEARDOWN] loader stopped")


def try_exec(path):
    """Return 'allowed' or 'denied'."""
    try:
        subprocess.run([path], stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL, timeout=10)
        return "allowed"
    except PermissionError as e:
        if e.errno != errno.EPERM:
            raise
        return "denied"


def open_trace():
    return os.open(TRACE_PIPE, os.O_RDONLY | os.O_NONBLOCK)


def read_trace(fd, settle_s=0.5):
    """Drain everything currently in trace_pipe."""
    time.sleep(settle_s)
    chunks = []
    while True:
        try:
            data = os.read(fd, 65536)
        except BlockingIOError:
            break
        if not data:
            break
        chunks.append(data)
    return b"".join(chunks).decode(errors="replace")


MEMORY_GUARDIANS = {
    "mmap_file": ["RWX mmap", "EXEC mmap on MAP_SHARED"],
    "mmap_addr": ["low-address mapping"],
    "file_mprotect": ["PROT_EXEC on MAP_SHARED region",
                      "region is currently PROT_WRITE",
                      "has been PROT_WRITE in past"],
}

# Ordinary workloads: they load shared libraries (private read+exec mappings),
# allocate anonymous read/write memory and run RELRO mprotect calls.
# None of this should ever be flagged by the memory guardians.
WORKLOADS = [
    [ALLOWED_TEST_BIN, "-la", "/"],
    ["/usr/bin/sh", "-c", "true"],
    [os.path.realpath(sys.executable), "-c", "import json, ssl, sqlite3"],
    [os.path.realpath(sys.executable), "-c",
     "import mmap; m = mmap.mmap(-1, 1 << 20); m[:5] = b'hello'; m.close()"],
]
WORKLOAD_COMMS = {os.path.basename(w[0])[:15] for w in WORKLOADS}


def trace_comm(line):
    """Task name from a trace_pipe line: '   ls-1234  [002] ...: msg'."""
    head = line.split("[", 1)[0].strip()
    return head.rsplit("-", 1)[0]


def run_workloads():
    for cmd in WORKLOADS:
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=30)


results = []

def check(name, got, expected):
    ok = got == expected
    results.append(ok)
    print(f"[{'PASS' if ok else 'FAIL'}] {name}: expected {expected}, got {got}")


# ---------------------------------------------------------------- main

def main():
    parser = argparse.ArgumentParser(description="guardian nominal PoC test")
    parser.add_argument("loader", help="path of the guardian loader binary")
    parser.add_argument("--enforce", action="store_true",
                        help="run the loader in enforce mode (default: log-only)")
    parser.add_argument("--whitelist", default=DEFAULT_WHITELIST,
                        help=f"whitelist file the loader reads (default: {DEFAULT_WHITELIST})")
    opts = parser.parse_args()

    if os.geteuid() != 0:
        sys.exit("[ERROR] run as root: sudo python3 test_guardian.py <loader>")
    if not os.access(opts.loader, os.X_OK):
        sys.exit(f"[ERROR] {opts.loader} is not an executable")

    mode = "ENFORCE" if opts.enforce else "LOG-ONLY"
    print(f"[SETUP] mode: {mode}")

    write_whitelist(opts.whitelist)
    loader = start_loader(opts.loader, opts.enforce)
    trace_fd = open_trace()

    try:
        read_trace(trace_fd, settle_s=0)   # discard anything logged before the tests

        check("whitelisted binary executes", try_exec(ALLOWED_TEST_BIN), "allowed")

        if opts.enforce:
            check("non-whitelisted binary is denied", try_exec(DENIED_TEST_BIN), "denied")
        else:
            check("non-whitelisted binary still executes (log-only)",
                  try_exec(DENIED_TEST_BIN), "allowed")
            marker = f"Execution blocked for {DENIED_TEST_BIN}"
            logged = any(marker in line for line in read_trace(trace_fd).splitlines())
            check("guardian logged the deny for the non-whitelisted binary",
                  "logged" if logged else "not logged", "logged")

        # memory guardians: ordinary programs must not trigger any of them
        read_trace(trace_fd, settle_s=0)   # start from a clean pipe
        run_workloads()
        lines = [l for l in read_trace(trace_fd).splitlines()
                 if "[GUARDIAN]" in l and trace_comm(l) in WORKLOAD_COMMS]

        for guardian, markers in MEMORY_GUARDIANS.items():
            hits = [l.strip() for l in lines if any(m in l for m in markers)]
            check(f"{guardian}: no false positives on ordinary programs",
                  f"{len(hits)} hits", "0 hits")
            for h in hits:
                print(f"         {h}")
    finally:
        os.close(trace_fd)
        stop_loader(loader)

    check("binary executes after detach", try_exec(DENIED_TEST_BIN), "allowed")

    passed = sum(results)
    print(f"\n{passed}/{len(results)} checks passed ({mode})")
    return 0 if passed == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())